### PR TITLE
adding nsec login and warnings

### PR DESCRIPTION
**Pull request by shoupn**
Adding a button and workflow for login using nsec(privkey) with ample warning. Includes some refactoring of buttons for this and using identity to check which to render on the Home.tsx. 
image

### CODE REVIEW

**Comment by arkin0x** [comment]
@shoupn great work! Hey, I was not able to publish a place when I used nsec login. It failed silently. I would check the console but I'm stuck on mobile right now. Check into it

**Comment by shoupn** [comment]
@arkin0x I'll look into it this evening. Thanks for testing through.

**Comment by shoupn** [comment]
Silly me. I didn't pass in the right PK, I used the nsec, not the hex pk. 

image

**Comment by arkin0x** [comment]
@shoupn Hey! I'm sorry but I still can't publish a place.

Here is a video of me running your branch locally and trying to publish a place with a newly generated nsec: https://youtu.be/c61LnKkfnU8

I have the exact same issue with the Vercel deployment of your nsec-login branch.

I tried:
- setting a password
- not setting a password
- editing the default place before publishing

To no effect. ☹

The relays are rejecting the event. I haven't looked into why this is, but maybe that would be a good place for you to start.

Tip: I'm using https://nak.nostr.com to generate a random nsec.

Can you try logging in with a random nsec to see if it works for you to publish a place?

**Comment by shoupn** [comment]
@arkin0x I just tested through using a new nsec. I was able to reproduce the same. I think there was something still cached on environment even after clearing localstorage. Apologies. It should be corrected with the last commit. 
https://github.com/innovatario/yondar-mono/pull/15/commits/3e510bc06ada47ff2ef13edddd0483715973c16b

**Pull request merged**
